title                    : "Naoki Sada | Neuroscience PhD Student"
description              : "PhD student at Osaka University studying neurodegeneration, protein aggregation, and active inference | JSPS Research Fellow (DC1)"
url                      : "https://nsada2025.github.io"
baseurl                  : ""
repository               : "NSada2025/academic-website"

locale                   : "en-US"
remote_theme             : academicpages/academicpages.github.io

navbar-links:
  About Me: "/"
  CV: "/cv/"
  Learning Journey: "/learning/"

author:
  name             : "Naoki Sada, M.D."
  avatar           : "https://avatars.githubusercontent.com/u/175803742"  # GitHub avatar as stable fallback
  bio              : "3rd year PhD student studying neurodegeneration and protein aggregation at Osaka University | JSPS Research Fellow (DC1)"
  location         : "Osaka, Japan"
  email            : "naoki.s.sound.of.sil@gmail.com"
  github           : "nsada2025"
  googlescholar    : "https://scholar.google.com/citations?user=PwHtFqYAAAAJ&hl=ja"
  researchmap      : "https://researchmap.jp/NSada_Myportal"
  twitter          : "NSada2025"

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

include:
  - _pages
exclude:
  - .github
  - node_modules
  - vendor

collections:
  teaching:
    output: true
  publications:
    output: true
  talks:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
