title                    : "Naoki Sada | Neuroscience PhD Student"
description              : "PhD student at Osaka University studying neurodegeneration, protein aggregation, and active inference | JSPS Research Fellow (DC1)"
url                      : "https://NSada2025.github.io"
baseurl                  : "/academic-website"
repository               : "NSada2025/academic-website"

locale                   : "en-US"
remote_theme             : "academicpages/academicpages.github.io"
# theme                    : "minimal-mistakes-jekyll"  # Comment out for GitHub Pages

# Navigation is configured in _data/navigation.yml

author:
  name             : "Naoki Sada, M.D."
  avatar           : "https://avatars.githubusercontent.com/u/175803742"  # GitHub avatar as stable fallback
  bio              : "3rd year PhD student studying neurodegeneration and protein aggregation at Osaka University | JSPS Research Fellow (DC1)"
  location         : "Osaka, Japan"
  email            : "naoki.s.sound.of.sil@gmail.com"
  github           : "nsada2025"
  googlescholar    : "https://scholar.google.com/citations?user=PwHtFqYAAAAJ&hl=ja"
  researchmap      : "https://researchmap.jp/NSada_Myportal"
  twitter          : "n____sally"
  note             : "https://note.com/n____sally"

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

# Read more link
read_more: "enabled"
excerpt_separator: "<!--more-->"

include:
  - _pages
exclude:
  - .github
  - node_modules
  - vendor

collections:
  teaching:
    output: true
  publications:
    output: true
  talks:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-redirect-from
  - jemoji
