title                    : "Naoki Sada's Academic Page"
description              : "Learning journey and research"
url                      : "https://nsada2025.github.io"
baseurl                  : "/academic-website"
repository               : "nsada2025/academic-website"

locale                   : "en-US"
remote_theme             : academicpages/academicpages.github.io

navbar-links:
  About Me: "/"
  CV: "/cv/"
  Learning Journey: "/learning/"

author:
  name             : "Naoki Sada"
  avatar           : "profile.png"
  bio              : "PhD student in neuroscience"
  email            : "none@example.org"
  github           : "nsada2025"
  googlescholar    : "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  orcid            : "http://orcid.org/yourorcidurl"

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

include:
  - _pages
exclude:
  - .github
  - node_modules
  - vendor

collections:
  teaching:
    output: true
  publications:
    output: true
  talks:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
